THREE.OrbitControls=function(h,H){function A(){return Math.pow(.95,a.zoomSpeed)}function C(b){a.object.isPerspectiveCamera||(a.object.isOrthographicCamera?(a.object.zoom=Math.max(a.minZoom,Math.min(a.maxZoom,a.object.zoom*b)),a.object.updateProjectionMatrix(),B=!0):(console.warn("WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled."),a.enableZoom=!1))}function I(b){a.object.isPerspectiveCamera||(a.object.isOrthographicCamera?(a.object.zoom=Math.max(a.minZoom,Math.min(a.maxZoom,
a.object.zoom/b)),a.object.updateProjectionMatrix(),B=!0):(console.warn("WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled."),a.enableZoom=!1))}function J(b){if(!1!==a.enabled){b.preventDefault();switch(b.button){case a.mouseButtons.ORBIT:if(!1===a.enableRotate)return;m.set(b.clientX,b.clientY);d=c.ROTATE;break;case a.mouseButtons.ZOOM:if(!1===a.enableZoom)return;n.set(b.clientX,b.clientY);d=c.DOLLY;break;case a.mouseButtons.PAN:if(!1===a.enablePan)return;p.set(b.clientX,
b.clientY);d=c.PAN}d!==c.NONE&&(document.addEventListener("mousemove",D,!1),document.addEventListener("mouseup",E,!1),a.dispatchEvent(F))}}function D(b){if(!1!==a.enabled)switch(b.preventDefault(),d){case c.ROTATE:if(!1===a.enableRotate)break;q.set(b.clientX,b.clientY);r.subVectors(q,m).multiplyScalar(a.rotateSpeed);b=a.domElement===document?a.domElement.body:a.domElement;e.theta-=2*Math.PI*r.x/b.clientHeight;e.phi-=2*Math.PI*r.y/b.clientHeight;m.copy(q);a.update();break;case c.DOLLY:if(!1===a.enableZoom)break;
t.set(b.clientX,b.clientY);y.subVectors(t,n);0<y.y?C(A()):0>y.y&&I(A());n.copy(t);a.update();break;case c.PAN:!1!==a.enablePan&&(u.set(b.clientX,b.clientY),v.subVectors(u,p).multiplyScalar(a.panSpeed),w(v.x,v.y),p.copy(u),a.update())}}function E(b){!1!==a.enabled&&(document.removeEventListener("mousemove",D,!1),document.removeEventListener("mouseup",E,!1),a.dispatchEvent(G),d=c.NONE)}function K(b){!1===a.enabled||!1===a.enableZoom||d!==c.NONE&&d!==c.ROTATE||(b.preventDefault(),b.stopPropagation(),
a.dispatchEvent(F),0>b.deltaY?I(A()):0<b.deltaY&&C(A()),a.update(),a.dispatchEvent(G))}function L(b){if(!1!==a.enabled&&!1!==a.enableKeys&&!1!==a.enablePan)switch(b.keyCode){case a.keys.UP:w(0,a.keyPanSpeed);a.update();break;case a.keys.BOTTOM:w(0,-a.keyPanSpeed);a.update();break;case a.keys.LEFT:w(a.keyPanSpeed,0);a.update();break;case a.keys.RIGHT:w(-a.keyPanSpeed,0),a.update()}}function M(b){if(!1!==a.enabled){b.preventDefault();switch(b.touches.length){case 1:if(!1===a.enableRotate)return;m.set(b.touches[0].pageX,
b.touches[0].pageY);d=c.TOUCH_ROTATE;break;case 2:if(!1===a.enableZoom&&!1===a.enablePan)return;if(a.enableZoom){var f=b.touches[0].pageX-b.touches[1].pageX,g=b.touches[0].pageY-b.touches[1].pageY;n.set(0,Math.sqrt(f*f+g*g))}a.enablePan&&p.set(.5*(b.touches[0].pageX+b.touches[1].pageX),.5*(b.touches[0].pageY+b.touches[1].pageY));d=c.TOUCH_DOLLY_PAN;break;default:d=c.NONE}d!==c.NONE&&a.dispatchEvent(F)}}function N(b){if(!1!==a.enabled)switch(b.preventDefault(),b.stopPropagation(),b.touches.length){case 1:if(!1===
a.enableRotate)break;if(d!==c.TOUCH_ROTATE)break;q.set(b.touches[0].pageX,b.touches[0].pageY);r.subVectors(q,m).multiplyScalar(a.rotateSpeed);b=a.domElement===document?a.domElement.body:a.domElement;e.theta-=2*Math.PI*r.x/b.clientHeight;e.phi-=2*Math.PI*r.y/b.clientHeight;m.copy(q);a.update();break;case 2:if(!1===a.enableZoom&&!1===a.enablePan)break;if(d!==c.TOUCH_DOLLY_PAN)break;if(a.enableZoom){var f=b.touches[0].pageX-b.touches[1].pageX,g=b.touches[0].pageY-b.touches[1].pageY;t.set(0,Math.sqrt(f*
f+g*g));y.set(0,Math.pow(t.y/n.y,a.zoomSpeed));C(y.y);n.copy(t)}a.enablePan&&(u.set(.5*(b.touches[0].pageX+b.touches[1].pageX),.5*(b.touches[0].pageY+b.touches[1].pageY)),v.subVectors(u,p).multiplyScalar(a.panSpeed),w(v.x,v.y),p.copy(u));a.update();break;default:d=c.NONE}}function O(b){!1!==a.enabled&&(a.dispatchEvent(G),d=c.NONE)}function P(b){!1!==a.enabled&&b.preventDefault()}this.object=h;this.domElement=void 0!==H?H:document;this.enabled=!0;this.target=new THREE.Vector3;this.minDistance=0;this.maxDistance=
Infinity;this.minZoom=0;this.maxZoom=Infinity;this.minPolarAngle=0;this.maxPolarAngle=Math.PI;this.minAzimuthAngle=-Infinity;this.maxAzimuthAngle=Infinity;this.enableDamping=!1;this.dampingFactor=.25;this.enableZoom=!0;this.zoomSpeed=1;this.enableRotate=!0;this.rotateSpeed=1;this.enablePan=!0;this.panSpeed=1;this.screenSpacePanning=!1;this.keyPanSpeed=7;this.autoRotate=!1;this.autoRotateSpeed=2;this.enableKeys=!0;this.keys={LEFT:37,UP:38,RIGHT:39,BOTTOM:40};this.mouseButtons={ORBIT:THREE.MOUSE.LEFT,
ZOOM:THREE.MOUSE.MIDDLE,PAN:THREE.MOUSE.RIGHT};this.target0=this.target.clone();this.position0=this.object.position.clone();this.zoom0=this.object.zoom;this.getPolarAngle=function(){return k.phi};this.getAzimuthalAngle=function(){return k.theta};this.saveState=function(){a.target0.copy(a.target);a.position0.copy(a.object.position);a.zoom0=a.object.zoom};this.reset=function(){a.target.copy(a.target0);a.object.position.copy(a.position0);a.object.zoom=a.zoom0;a.object.updateProjectionMatrix();a.dispatchEvent(Q);
a.update();d=c.NONE};this.update=function(){var b=new THREE.Vector3,f=(new THREE.Quaternion).setFromUnitVectors(h.up,new THREE.Vector3(0,1,0)),g=f.clone().inverse(),l=new THREE.Vector3,x=new THREE.Quaternion;return function(V){var R=a.object.position;b.copy(R).sub(a.target);b.applyQuaternion(f);V&&k.setFromVector3(b);a.autoRotate&&d===c.NONE&&(e.theta-=2*Math.PI/60/60*a.autoRotateSpeed);k.theta+=e.theta;k.phi+=e.phi;k.theta=Math.max(a.minAzimuthAngle,Math.min(a.maxAzimuthAngle,k.theta));k.phi=Math.max(a.minPolarAngle,
Math.min(a.maxPolarAngle,k.phi));k.makeSafe();k.radius=4;a.target.add(z);b.setFromSpherical(k);b.applyQuaternion(g);R.copy(a.target).add(b);a.object.lookAt(a.target);!0===a.enableDamping?(e.theta*=1-a.dampingFactor,e.phi*=1-a.dampingFactor,z.multiplyScalar(1-a.dampingFactor)):(e.set(0,0,0),z.set(0,0,0));return B||l.distanceToSquared(a.object.position)>S||8*(1-x.dot(a.object.quaternion))>S?(a.dispatchEvent(Q),l.copy(a.object.position),x.copy(a.object.quaternion),B=!1,!0):!1}}();this.dispose=function(){a.domElement.removeEventListener("contextmenu",
P,!1);a.domElement.removeEventListener("mousedown",J,!1);a.domElement.removeEventListener("wheel",K,!1);a.domElement.removeEventListener("touchstart",M,!1);a.domElement.removeEventListener("touchend",O,!1);a.domElement.removeEventListener("touchmove",N,!1);document.removeEventListener("mousemove",D,!1);document.removeEventListener("mouseup",E,!1);window.removeEventListener("keydown",L,!1)};var a=this,Q={type:"change"},F={type:"start"},G={type:"end"},c={NONE:-1,ROTATE:0,DOLLY:1,PAN:2,TOUCH_ROTATE:3,
TOUCH_DOLLY_PAN:4},d=c.NONE,S=1E-6,k=new THREE.Spherical,e=new THREE.Spherical,z=new THREE.Vector3,B=!1,m=new THREE.Vector2,q=new THREE.Vector2,r=new THREE.Vector2,p=new THREE.Vector2,u=new THREE.Vector2,v=new THREE.Vector2,n=new THREE.Vector2,t=new THREE.Vector2,y=new THREE.Vector2,T=function(){var b=new THREE.Vector3;return function(f,g){b.setFromMatrixColumn(g,0);b.multiplyScalar(-f);z.add(b)}}(),U=function(){var b=new THREE.Vector3;return function(f,g){!0===a.screenSpacePanning?b.setFromMatrixColumn(g,
1):(b.setFromMatrixColumn(g,0),b.crossVectors(a.object.up,b));b.multiplyScalar(f);z.add(b)}}(),w=function(){var b=new THREE.Vector3;return function(f,g){var l=a.domElement===document?a.domElement.body:a.domElement;if(a.object.isPerspectiveCamera){b.copy(a.object.position).sub(a.target);var x=b.length();x*=Math.tan(a.object.fov/2*Math.PI/180);T(2*f*x/l.clientHeight,a.object.matrix);U(2*g*x/l.clientHeight,a.object.matrix)}else a.object.isOrthographicCamera?(T(f*(a.object.right-a.object.left)/a.object.zoom/
l.clientWidth,a.object.matrix),U(g*(a.object.top-a.object.bottom)/a.object.zoom/l.clientHeight,a.object.matrix)):(console.warn("WARNING: OrbitControls.js encountered an unknown camera type - pan disabled."),a.enablePan=!1)}}();a.domElement.addEventListener("contextmenu",P,!1);a.domElement.addEventListener("mousedown",J,!1);a.domElement.addEventListener("wheel",K,!1);a.domElement.addEventListener("touchstart",M,!1);a.domElement.addEventListener("touchend",O,!1);a.domElement.addEventListener("touchmove",
N,!1);window.addEventListener("keydown",L,!1)};THREE.OrbitControls.prototype=Object.create(THREE.EventDispatcher.prototype);THREE.OrbitControls.prototype.constructor=THREE.OrbitControls;
Object.defineProperties(THREE.OrbitControls.prototype,{center:{get:function(){console.warn("THREE.OrbitControls: .center has been renamed to .target");return this.target}},noZoom:{get:function(){console.warn("THREE.OrbitControls: .noZoom has been deprecated. Use .enableZoom instead.");return!this.enableZoom},set:function(h){console.warn("THREE.OrbitControls: .noZoom has been deprecated. Use .enableZoom instead.");this.enableZoom=!h}},noRotate:{get:function(){console.warn("THREE.OrbitControls: .noRotate has been deprecated. Use .enableRotate instead.");
return!this.enableRotate},set:function(h){console.warn("THREE.OrbitControls: .noRotate has been deprecated. Use .enableRotate instead.");this.enableRotate=!h}},noPan:{get:function(){console.warn("THREE.OrbitControls: .noPan has been deprecated. Use .enablePan instead.");return!this.enablePan},set:function(h){console.warn("THREE.OrbitControls: .noPan has been deprecated. Use .enablePan instead.");this.enablePan=!h}},noKeys:{get:function(){console.warn("THREE.OrbitControls: .noKeys has been deprecated. Use .enableKeys instead.");
return!this.enableKeys},set:function(h){console.warn("THREE.OrbitControls: .noKeys has been deprecated. Use .enableKeys instead.");this.enableKeys=!h}},staticMoving:{get:function(){console.warn("THREE.OrbitControls: .staticMoving has been deprecated. Use .enableDamping instead.");return!this.enableDamping},set:function(h){console.warn("THREE.OrbitControls: .staticMoving has been deprecated. Use .enableDamping instead.");this.enableDamping=!h}},dynamicDampingFactor:{get:function(){console.warn("THREE.OrbitControls: .dynamicDampingFactor has been renamed. Use .dampingFactor instead.");
return this.dampingFactor},set:function(h){console.warn("THREE.OrbitControls: .dynamicDampingFactor has been renamed. Use .dampingFactor instead.");this.dampingFactor=h}}});